### ISSUE TITLE
Add preamble that uses existing installation of tsk

### ISSUE THREAD

**Issue by NightMachinery** [tsk-tsk/tsk-tsk#29]
I do not want a curl request everytime my scripts are run (both for offline access and security implications). I like to install tsk once, and use a preamble that uses this installation. 

Some unrelated questions:
- Does the preamble assume a particular shell is used to open the file? Which shell will be used? The value of $SHELL ?
- I could not find the documentation on compiling the script to a native binary.

**Comment by vic** [comment]
I tested using a preamble like the following:

```
// 2> /dev/null; source $(command -v tsk || curl -sL https://git.io/boot-tsk | sh); run; exit
```

This is assumming that the target user already has the tsk shell script somewhere in PATH.

Perhaps we could document something along this line. I also see value on not executing curl every time the user wants to run an utility.

**Comment by NightMachinery** [comment]
@vic `source` seems dangerous. Doesn't this line get executed by the user's current shell? What if it is not a POSIX shell?

**Comment by przemek-pokrywka** [comment]
Hi @vic @NightMachinary, TSK script isn't meant to be on the PATH. It is meant to be sourced and I agree with the sentiment that it may seem dangerous (really I think it wouldn't be dangerous because of the TSK content). I'm not able to give you some well-prepared preamble right now, but @vic was pretty close. The simplest thing that'd work is:
```
// 2> /dev/null; source $(ls ~/.tsk/tsk-trunk || curl -sL https://git.io/boot-tsk | sh); run; exit
```
because `ls` will only output on stderr in case the TSK is missing.

**Comment by przemek-pokrywka** [comment]
Hi @vic @NightMachinary, I've added a preable that does what's needed here:

https://github.com/tsk-tsk/tsk-tsk/wiki#offline-operation

Please let me know if the docs can be improved, I'll reopen the issue then.

**Comment by przemek-pokrywka** [comment]
Regarding the unaddressed parts of the original issue content:

> Some unrelated questions:
>
>    Does the preamble assume a particular shell is used to open the file? Which shell will be used? The value of $SHELL ?
>    I could not find the documentation on compiling the script to a native binary.

The shell is assumed to be POSIX compliant. I've tested with Bash, Ash and Dash. Fish is known to be non-working since it won't open a file without a shebang (I've described that in the "limitations" section). But perhaps the docs may state that more clearly, feel free to submit a PR with the improvements (the wiki can be cloned and hopefully forked as well).

Also the docs on the `native` variable are pretty hard to find (only in the variable reference so far), I'll be trying to improve the docs going forward.
